version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: twentyfourseven-db
    environment:
      POSTGRES_USER: twentyfourseven
      POSTGRES_PASSWORD: twentyfourseven
      POSTGRES_DB: twentyfourseven
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twentyfourseven"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: twentyfourseven-backend
    environment:
      DATABASE_URL: postgresql://twentyfourseven:twentyfourseven@postgres:5432/twentyfourseven?schema=public
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:3001
    container_name: twentyfourseven-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
